export const LOAD_CHRONO_CONFIGS = "LOAD_CHRONO_CONFIGS";
export const LOAD_CHRONO_CONFIGS_SUCCESS = "LOAD_CHRONO_CONFIGS_SUCCESS";
export const LOAD_CHRONO_CONFIGS_ERROR = "LOAD_CHRONO_CONFIGS_ERROR";

export const CREATE_ZONE = "CREATE_ZONE";
export const CREATE_ZONE_SUCCESS = "CREATE_ZONE_SUCCESS";
export const CREATE_ZONE_ERROR = "CREATE_ZONE_ERROR";

export const UPDATE_DAILY_SCHEDULE = "UPDATE_DAILY_SCHEDULE";
export const UPDATE_DAILY_SCHEDULE_SUCCESS = "UPDATE_DAILY_SCHEDULE_SUCCESS";
export const UPDATE_DAILY_SCHEDULE_ERROR = "UPDATE_DAILY_SCHEDULE_ERROR";

export const UPDATE_WORK_MODE = "UPDATE_WORK_MODE";
export const UPDATE_WORK_MODE_SUCCESS = "UPDATE_WORK_MODE_SUCCESS";
export const UPDATE_WORK_MODE_ERROR = "UPDATE_WORK_MODE_ERROR";

export const UPDATE_ZONE_DEVICES = "UPDATE_ZONE_DEVICES";
export const UPDATE_ZONE_DEVICES_SUCCESS = "UPDATE_ZONE_DEVICES_SUCCESS";
export const UPDATE_ZONE_DEVICES_ERROR = "UPDATE_ZONE_DEVICES_ERROR";